/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itu.panels;

import itu.ClientBean;
import itu.ClientFrame;
import itu.registration;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
*   Registrace
*
*/
public class RegistrationPanel extends javax.swing.JPanel {

    // odkaz na bean
    private ClientBean bean;
    
     /**
     * Creates new form registration
     */
    String log = "";
    String pswd = "";
    
    
    public RegistrationPanel(ClientBean bean) {
        this.bean = bean;
        
        initComponents();
    }

    public String getLog() {
        return log;
    }

    public String getPswd() {
        return pswd;
    }
    
    
    public void showErrorMessage(String msg) {
        jLabel3.setText(msg);
        jLabel3.setVisible(true);
    }
    
    public void clearErrorMessage(){
        jLabel3.setText("");
        jLabel3.setVisible(false);
    }

    @Override
    public void show(boolean b) {
        super.show(b); //To change body of generated methods, choose Tools | Templates.
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        int width = 150;
        
        // Center object in panel
        this.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        this.setBackground(Color.white);
        
        
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();


        
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        

        jButton1.setText("Registrate");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        
        // Registrate text
        jLabelRegistrace = new javax.swing.JLabel();
        jLabelRegistrace.setText("Registration");
        jLabelRegistrace.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jLabelRegistrace.setForeground(new Color(102, 102, 102));
        add(jLabelRegistrace, gbc);
        
        javax.swing.JPanel vypln0 = new javax.swing.JPanel();
        vypln0.setBackground(Color.white);
        vypln0.setPreferredSize(new Dimension(15, 15));
        add(vypln0, gbc);
        
        
        // Error
        clearErrorMessage();
        jLabel3.setForeground(new Color(174,50,50));
        add(jLabel3, gbc);
        
        
        
        // Login input
        jLabel1.setText("Username");
        add(jLabel1, gbc);
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204, 204, 204)));
        jTextField1.setPreferredSize(new Dimension(width, 30));
        add(jTextField1, gbc);
        
        javax.swing.JPanel vypln1 = new javax.swing.JPanel();
        vypln1.setBackground(Color.white);
        vypln1.setPreferredSize(new Dimension(15, 15));
        add(vypln1, gbc);
        
        // Password input
        jLabel2.setText("Password");
        add(jLabel2, gbc);
        jTextField2.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204, 204, 204)));
        jTextField2.setPreferredSize(new Dimension(width, 30));
        jTextField2.setEchoChar('*');
        add(jTextField2, gbc);
        
        javax.swing.JPanel vypln2 = new javax.swing.JPanel();
        vypln2.setBackground(Color.white);
        vypln2.setPreferredSize(new Dimension(30, 30));
        add(vypln2, gbc);
        
        // Register btn
        jButton1.setBackground(new Color(204, 204, 204));
        jButton1.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.white));
        jButton1.setForeground(new Color(102, 102, 102));
        jButton1.setPreferredSize(new Dimension(width, 30));
        add(jButton1, gbc);
        
        javax.swing.JPanel vypln3 = new javax.swing.JPanel();
        vypln3.setBackground(Color.white);
        vypln3.setPreferredSize(new Dimension(40, 40));
        add(vypln3, gbc);
        
    }// </editor-fold>                        

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
        
        clearErrorMessage();
        String empty = "";
        if ((jTextField1.getText()).equals(empty)) 
        {
            showErrorMessage("Fill all fields");
            jTextField1.setText("");
            jTextField1.requestFocus();
        } 
        else 
        {
            log =jTextField1.getText();
            
            String password = String.copyValueOf(jTextField2.getPassword());
            
            if ((password).equals(empty)) 
            {
                jTextField2.setText("");
                jTextField2.requestFocus();
                showErrorMessage("Fill all fields");
            } 
            else 
            {
                pswd =password;
                //int res = cl.try_connect(ret1(),ret2());
                System.out.format("black");
                int res = bean.getConnection().try_connect(log, pswd,0);
                
                if (res == 5) { // already exist
                    showErrorMessage("User already exists");
                }
                else if (res == 3) {// regisrace ok
                    JOptionPane.showMessageDialog(null, "Registration was successful. You can Sign in now.", "Registration", JOptionPane.INFORMATION_MESSAGE);
                    bean.getFrame().showLogin();
                }
                else {
                    showErrorMessage("Can't create new user");
                }
            }
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    private javax.swing.JLabel jLabelRegistrace;
    // End of variables declaration      
}
